export const coffees = [
  {
    img: 'Expresso',
    tagValue: ['TRADICIONAL'],
    textTitle: 'Expresso Tradicional',
    text: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
  },
  {
    img: 'Americano',
    tagValue: ['TRADICIONAL'],
    textTitle: 'Expresso Americano',
    text: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.9,
  },
  {
    img: 'ExpressoCremoso',
    tagValue: ['TRADICIONAL'],
    textTitle: 'Expresso Cremoso',
    text: 'Café expresso tradicional com espuma cremosa',
    price: 9.9,
  },
  {
    img: 'CafeGelado',
    tagValue: ['TRADICIONAL', 'GELADO'],
    textTitle: 'Expresso Gelado',
    text: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
  },
  {
    img: 'CafeComLeite',
    tagValue: ['TRADICIONAL', 'COM LEITE'],
    textTitle: 'Café com Leite',
    text: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.9,
  },
  {
    img: 'Latte',
    tagValue: ['TRADICIONAL', 'COM LEITE'],
    textTitle: 'Latte',
    text: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.9,
  },
  {
    img: 'Capuccino',
    tagValue: ['TRADICIONAL', 'COM LEITE'],
    textTitle: 'Capuccino',
    text: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.9,
  },
  {
    img: 'Macchiato',
    tagValue: ['TRADICIONAL', 'COM LEITE'],
    textTitle: 'Macchiato',
    text: 'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.9,
  },
  {
    img: 'Mochaccino',
    tagValue: ['TRADICIONAL', 'COM LEITE'],
    textTitle: 'Mocaccino',
    text: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
  },
  {
    img: 'ChocolateQuente',
    tagValue: ['ESPECIAL', 'COM LEITE'],
    textTitle: 'Chocolate Quente',
    text: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
  },
  {
    img: 'Cubano',
    tagValue: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    textTitle: 'Cubano',
    text: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
  },
  {
    img: 'Havaiano',
    tagValue: ['ESPECIAL'],
    textTitle: 'Havaiano',
    text: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
  },
  {
    img: 'Arabe',
    tagValue: ['ESPECIAL'],
    textTitle: 'Árabe',
    text: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
  },
  {
    img: 'Irlandes',
    tagValue: ['ESPECIAL', 'ALCOÓLICO'],
    textTitle: 'Irlandês',
    text: 'Bebida à base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
  },
] as const
